### ISSUE TITLE
Command to suppress uninstall failure if extension does not exist?

### ISSUE THREAD

**Issue by tgeng** [microsoft/vsixbootstrapper#17]
With `/u`, the bootstrapper returns non-zero exit code if the extension does not exist. It would be nice if there is a flag like `ignoreIfNotExist`.

Background: I am trying to properly install and uninstall an extension with a WiX installer. I have been following https://github.com/Microsoft/vsixbootstrapper/wiki/Samples but uninstall would fail if the extension has already been removed. I see https://github.com/Microsoft/vsixbootstrapper/issues/3 and it seems the proper way of using `DetectCondition` won't happen anytime soon. So would it be easier to have such a flag instead?

**Comment by heaths** [comment]
This tool is merely a wrapper for VSIXInstaller.exe that passes any command line arguments to VSIXInstaller.exe and returns it's return code. To request changes, please open an issue at https://developercommunity.visualstudio.com.
