### ISSUE TITLE
VSIX Installer : Initializing...

### ISSUE THREAD

**Issue by febitanya** [Microsoft/vsixbootstrapper#25]
when trying install qqqq.vsix ( for visual studio 2022  ) ;
* on screen writing "Initializing..."
this Initializing process is not finishing after 30min

![VSIX Installer - Initializing](https://user-images.githubusercontent.com/7389743/160361573-8c91ca86-2208-424f-8cf0-0a3cf23425ec.png)
s

**Comment by heaths** [comment]
The VSIXBootstrapper just runs the VSIXInstaller. If you're having an issue with the installer itself, please file feedback from within Visual Studio to collect enough information for teams to diagnose the issue.

**Comment by Object-wty** [comment]
I have this problem too, what did you do to solve it

**Comment by heaths** [comment]
@Object-wty, please follow my recommendation in the [comment above](https://github.com/microsoft/vsixbootstrapper/issues/25#issuecomment-1080912534). More information will be needed that the feedback system will collect.
